server:
  port: 8800
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://117.72.179.87:3306/blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    database: 8


#==============================knife4j配置==============================
knife4j:
  enable: true
  basic:
    enable: true
    username: test
    password: 123456
  openapi:
    title: 韋博客接口文档
    description: 一个专注于技术分享的博客平台
    # aaa"
    email: 1774532899@qq.com
    concat: 韋
    url: https://blog-server.wcgmallcwj.online/doc.html
    version: v1.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.mojian

#==============================公众号配置==============================
wechat:
  app-id: wx66610ae6a45de497
  # 公众号AppSecret
  secret: 9631b5c8d542556f5bc542328618015c
  # 公众号Token
  token: cwj
  # 公众号AES Key
  aesKey: EsolspotIfizscSLU7NqnlYIwcYoYmzZALRMv65DcBr

  appletAppId:
  appletSecret:

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey: afc59328-3eb7-4414-a800-38cde2292bca
  baseUrl: https://ark.cn-beijing.volces.com/api/v3
  # 推理接入点ID
  model: ep-20250811101710-glvvc

#==============================邮箱配置=======================================
mail:
  smtp:
    host: smtp.163.com
    port: 25
    email: chenweijiang_1203@163.com
    password: CQex8Hr8VJvVSiFD

#============================第三方登录配置信息===================================
qq:
  app-id:
  app-secret:
  redirect-url: http://blog-server.wcgmallcwj.online/api/auth/callback/qq
weibo:
  app-id:
  app-secret:
  redirect-url:  1111

gitee:
  app-id: 4d9b0dcb415a5bda3bf926adde953e4b9cc9316efd89ecbcd523ea4d792e99cc
  app-secret: a73339c446e43a87970a57adcadd929b4d7d8fc3472770ded119b62cdb153b4e
  redirect-url: https://blog-server.wcgmallcwj.online/api/auth/callback/gitee

github:
  app-id: Ov23liuq94w75TUbk1ZO
  app-secret: e30ab9a35e0888eb9d76c04460f374d694cfe1c1
  redirect-url: https://blog-server.wcgmallcwj.online/api/auth/callback/github
#==============================聚合登录配置信息===================================
juhe:
  id: 10008450
  key: 86b9b28af476d230a39d3acb574c01eb
  login-url: https://cn.apihz.cn/api/user/jhdl.php
  check-login-url: https://cn.apihz.cn/api/user/jhdlq.php
  return-url: https://blog-server.wcgmallcwj.online/api/juhe/checkLogin/
#  return-url: http://localhost:8800/api/juhe/checkLogin/
front:
  url: https://blog-web.wcgmallcwj.online/
#  url: http://localhost:3000/
