server:
  port: 8800
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    database: 8


#==============================knife4j配置==============================
knife4j:
  enable: true
  basic:
    enable: true
    username: test
    password: 123456
  openapi:
    title: 韋博客接口文档
    description: 一个专注于技术分享的博客平台
    # aaa"
    email: 1774532899@qq.com
    concat: 韋
    url: https://blog-server.wcgmallcwj.online/doc.html
    version: v1.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.mojian

#==============================公众号配置==============================
wechat:
  app-id: 
  # 公众号AppSecret
  secret: 
  # 公众号Token
  token: 
  # 公众号AES Key
  aesKey: 

  appletAppId:
  appletSecret:

#==============================豆包推理AI配置=======================================
ai:
  # API Key
  apiKey: 
  baseUrl: 
  # 推理接入点ID
  model: 

#==============================邮箱配置=======================================
mail:
  smtp:
    host: smtp.163.com
    port: 25
    email: 
    password: 

#============================第三方登录配置信息===================================
qq:
  app-id:
  app-secret:
  redirect-url: http://blog-server.wcgmallcwj.online/api/auth/callback/qq
weibo:
  app-id:
  app-secret:
  redirect-url:  1111

gitee:
  app-id: 
  app-secret: 
  redirect-url: https://blog-server.wcgmallcwj.online/api/auth/callback/gitee

github:
  app-id:
  app-secret: 
  redirect-url: https://blog-server.wcgmallcwj.online/api/auth/callback/github
#==============================聚合登录配置信息===================================
juhe:
  id: 
  key: 
  login-url: https://cn.apihz.cn/api/user/jhdl.php
  check-login-url: https://cn.apihz.cn/api/user/jhdlq.php
  return-url: https://blog-server.wcgmallcwj.online/api/juhe/checkLogin/
#  return-url: http://localhost:8800/api/juhe/checkLogin/
front:
  url: https://blog-web.wcgmallcwj.online/
#  url: http://localhost:3000/
